name: Build KernelSU Next for Xiaomi 12T Pro (diting)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git bc bison flex build-essential libssl-dev \
            libelf-dev ccache python3 unzip lz4 libncurses5-dev \
            libncursesw5-dev clang wget

      - name: Clone kernel source
        run: |
          git clone https://github.com/Xiaomi-Diting-Development/android_kernel_xiaomi_diting.git kernel --depth=1

      - name: Clone stable KernelSU (v11200) into kernel directory
        run: |
          cd kernel
          git clone --branch v11200 https://github.com/tiann/KernelSU.git KernelSU --depth=1

      - name: Apply KernelSU patch
        run: |
          cd kernel
          bash KernelSU/tools/patch.sh

      - name: Setup Clang and build
        run: |
          cd kernel
          git clone https://github.com/ClangBuiltLinux/linux-toybox clang --depth=1
          export ARCH=arm64
          export SUBARCH=arm64
          export PATH="$PWD/clang/bin:$PATH"
          make vendor/diting_defconfig
          make -j$(nproc)

      - name: Upload Image.gz-dtb
        uses: actions/upload-artifact@v4
        with:
          name: image-gz-dtb
          path: kernel/arch/arm64/boot/Image.gz-dtb
