name: Build KernelSU Next for Xiaomi 12T Pro (diting)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git bc bison flex build-essential libssl-dev \
            libelf-dev ccache python3 unzip lz4 libncurses5-dev \
            libncursesw5-dev clang wget curl

      - name: Clone kernel source
        run: |
          git clone https://github.com/Xiaomi-Diting-Development/android_kernel_xiaomi_diting.git kernel --depth=1

      - name: Apply KernelSU patch (latest stable)
        run: |
          cd kernel
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

      - name: Download and extract Google Clang
        run: |
          cd kernel
          mkdir clang
          cd clang
          curl -O https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/master/clang-r450784d.tar.gz
          tar -xf clang-r450784d.tar.gz

      - name: Build kernel
        run: |
          cd kernel
          export ARCH=arm64
          export SUBARCH=arm64
          export PATH="$PWD/clang/bin:$PATH"
          make vendor/diting_defconfig
          make -j$(nproc)

      - name: Upload compiled kernel Image.gz-dtb
        uses: actions/upload-artifact@v4
        with:
          name: image-gz-dtb
          path: kernel/arch/arm64/boot/Image.gz-dtb
